### ISSUE TITLE
Is there a way to download an incomplete torrent? Such as one stuck at 99%

### ISSUE THREAD

**Issue by bnichs5** [Lunik/tcloud#106]
Hi. Great work. Quick question.  Is there a way to download an incomplete torrent? Sometimes I get one that is stuck at 99% and won't finish. If there isn't a a way could you create one?  Thanks in advance!

**Comment by Lunik** [comment]
Try to re-download it a second time with removing the first one

**Comment by bnichs5** [comment]
Thanks for the quick reply. It's because the seeder stops it at 99% on purpose so this wouldn't help.

**Comment by bnichs5** [comment]
I'm not sure why the original seeder does this but I'd like to be able to download the files that are completed. It's just that the whole torrent didn't completely download.
